version: '3.8'

services: 
  traefik:
    image: "traefik:v2.4"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  app:
    image: dejandayoff/wedding-backend
    restart: always
    env_file: .env
    volumes: 
      - ./app/logs:/app/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/v1/`)"
      - "traefik.http.routers.backend.entrypoints=web"